services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SENTRY_DSN: ${SENTRY_DSN:-}

  grafana:
    ports:
      - "3000:3000"
