services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

  postgres:
    ports:
      - "5432:5432"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"
