global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: click-checker-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - app:8080
        labels:
          app: app

  - job_name: click-checker-renderer
    metrics_path: /metrics
    static_configs:
      - targets:
          - renderer:8081
        labels:
          app: renderer
