CREATE TABLE route_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    template VARCHAR(512) NOT NULL,
    route_key VARCHAR(512) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_route_templates_org_template UNIQUE (organization_id, template),
    CONSTRAINT fk_route_templates_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id)
);
