CREATE TABLE organization_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_organization_members_account
        FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_organization_members_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT uk_organization_members_account_organization
        UNIQUE (account_id, organization_id),
    CONSTRAINT organization_members_role_check
        CHECK (role IN ('OWNER', 'ADMIN', 'VIEWER'))
);

CREATE INDEX idx_organization_members_account_id
    ON organization_members (account_id);

CREATE INDEX idx_organization_members_organization_id
    ON organization_members (organization_id);
