CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    api_key_created_at TIMESTAMPTZ,
    api_key_hash VARCHAR(64),
    api_key_kid VARCHAR(32),
    api_key_last_used_at TIMESTAMPTZ,
    api_key_prefix VARCHAR(16),
    api_key_rotated_at TIMESTAMPTZ,
    api_key_status VARCHAR(16),
    CONSTRAINT organizations_api_key_status_check
        CHECK (api_key_status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT uk5g2sfqsteqy2okiwu2gvrihxj UNIQUE (api_key_hash),
    CONSTRAINT ukr7p17pg4ku76qejsl6x43hpd UNIQUE (api_key_kid)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_user_id VARCHAR(100) NOT NULL,
    organization_id BIGINT NOT NULL,
    CONSTRAINT uk_users_org_external_user_id UNIQUE (organization_id, external_user_id),
    CONSTRAINT fkqpugllwvyv37klq7ft9m8aqxk
        FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    path VARCHAR(512),
    payload OID,
    event_user_id BIGINT,
    organization_id BIGINT NOT NULL,
    CONSTRAINT fkfufxqjayc739da0lxlx54ts7y
        FOREIGN KEY (event_user_id) REFERENCES users (id),
    CONSTRAINT fkghg7dncn6gxt9fafba44f52b6
        FOREIGN KEY (organization_id) REFERENCES organizations (id)
);
